version: 2

updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    labels:
      - Dependencies
    allow:
      - dependency-type: direct
    commit-message:
      prefix: chore
      prefix-development: chore
