version: 2

updates:
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "yeldiRium"
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
