version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_assignees:
      - "yeldiRium"
    allowed_updates:
      - match:
          dependency_type: "direct"
          update_type: "all"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
    version_requirement_updates: "increase_versions"
