version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_assignees:
      - "yeldiRium"
    allowed_updates:
      - match:
          dependency_type: "direct"
          update_type: "all"
    version_requirement_updates: "increase_versions"
