name: Test

on: pull_request

jobs:
  qa:
    name: Test
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Use Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Run QA
        run: |
          make qa
